purple:
  - Citi
  - York
  - Taft
  - Medgar
  - Wingate
  - Capsule
  - Brandeis
  - Yankee
---
green:
  - Stony
  - Javits
  - Aqueduct
  - Westchester
  - Jones
---
site: http://turbovax.global.ssl.fastly.net/locations
