purple:
  - Citi
  - York
  - Taft
  - Medgar
---
green:
  - Staten
  - Richmond
---
site: http://spreadsheets.google.com/feeds/cells/1EHaZgbEPn1y5wKE4Enx65zIsIxSL7-bPIHvNcAKrMEo/3/public/full?alt=json