purple:
  - Citi
  - York
  - Taft
  - Medgar
  - Wingate
  - Capsule
  - Brandeis
  - Yankee
---
green:
  - Javits
  - Aqueduct
  - Westchester
  - Jones
---
site: http://spreadsheets.google.com/feeds/cells/1NNZJWI7BYlajdBcqkEpOXXq6EZZyMd-zSIGKHNgS99w/4/public/full?alt=json
